name: issue comments managment
on:
  issue_comment:
    types: [created, edited]
jobs:
  delete-comment:
    runs-on: ubuntu-latest
    steps:
      - id: find-comments
        name: Find comments
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'find-comments'
          body-includes: ${{ secrets.CLOSE_LOCK_ISSUE_TITLE_INCLUDES }}
      - name: Delete comment
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'delete-comment'
          out-comments: ${{ steps.find-comments.outputs }}
